mirror/urls.py
from django.conf.urls import url, include

from mirror import views

app_name = 'mirror'
urlpatterns = [
    url(r'^setter/$', views.setCookies, name='setter'),
    url(r'^season/(?P<seasonNum>[0-9]+)/series/(?P<seriesNum>[0-9]+)/v-originale',
        views.watchEngl, name='watchEngl'),
    url(r'^season/(?P<seasonNum>[0-9]+)/series/(?P<seriesNum>[0-9]+)',
        views.watch, name='watch'),
    url(r'^callback$', views.callback, name='callback'),
    url(r'^subscribe$', views.subscribe, name='subscribe'),
    url(r'^season-(?P<num>[0-9]+)$', views.seasonView, name='season'),
    url(r'^$', views.index, name='index'),
]

mr/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^', include('mirror.urls')),
    url(r'^admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mirror/models.py
from django.db import models


# Create your models here.


class season(models.Model):
    number = models.IntegerField()
    description = models.TextField(max_length=1000, default='some text')

    def __str__(self):
        return '%s %s' % (self.number, " season")


class seriesRus(models.Model):
    obj = models.ForeignKey(season, on_delete=models.CASCADE, null=True)
    name = models.CharField(max_length=200, default='name')
    nameEng = models.CharField(max_length=200, default='name')
    duration = models.CharField(max_length=50, default='30:25')
    season = models.IntegerField()
    number = models.IntegerField()
    description = models.TextField(max_length=1000, default='description')
    image = models.ImageField(upload_to='mirror/static/mirror/img/holder/', blank=True)
    video = models.CharField(max_length=500, default='static/')

    def save(self, *args, **kwargs):
        self.name = self.name.ljust(17)
        super(seriesRus, self).save(*args, **kwargs)

    def __str__(self):
        return '%s %s %s %s %s %s' % (self.name, " ", self.season, " season ", self.number, "series")


class seriesEng(models.Model):
    obj = models.OneToOneField(seriesRus, blank=True)
    video = models.CharField(max_length=500, default='static/')
    subtitlesRus = models.ImageField(upload_to='documents/subtitlesRus', blank=True)
    subtitlesEng = models.ImageField(upload_to='documents/subtitlesEng', blank=True)
    description = models.TextField(max_length=1000, default='description', blank=True)

    def __str__(self):
        return '%s %s %s %s %s %s' % (self.obj.name, " ", self.obj.season, " season ", self.obj.number, "series ENGL")


class subscribers(models.Model):
    email = models.EmailField()

    def __str__(self):
        return self.email


class questions(models.Model):
    name = models.CharField(max_length=300)
    email = models.EmailField()
    question = models.TextField()

    def __str__(self):
        return self.name

mirror/views.py
import datetime
from django.core.validators import validate_email
from django.forms import forms
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404

# Create your views here.
from mirror.models import season, seriesRus, subscribers, questions, seriesEng


def index(request):
    dictionary = {}
    listOfSeasons = season.objects.order_by('-number')
    for ses in listOfSeasons:
        listOfSeries = seriesRus.objects.filter(obj=ses).order_by('number')
        dictionary[ses.number] = listOfSeries

    response = render(request, 'mirror/index.html', {'dict': dictionary})
    try:
        ses = str(request.COOKIES['season'])
        ser = str(request.COOKIES['series'])
        lang = str(request.COOKIES['language'])

        response.set_cookie('season', ses, expires=(datetime.datetime.now() + datetime.timedelta(days=60)))
        response.set_cookie('series', ser, expires=(datetime.datetime.now() + datetime.timedelta(days=60)))
        response.set_cookie('language', lang, expires=(datetime.datetime.now() + datetime.timedelta(days=60)))
        response.set_cookie('beginner', 'no', expires=(datetime.datetime.now() + datetime.timedelta(days=60)))
    except KeyError:
        response.set_cookie('beginner', 'yes', expires=(datetime.datetime.now() + datetime.timedelta(days=60)))
    return response


def seasonView(request, num):
    currentSeason = get_object_or_404(season, number=int(num))
    series = seriesRus.objects.filter(obj=currentSeason).order_by('number')
    return render(request, 'mirror/season.html', {'season': currentSeason,
                                                  'series': series,
                                                  'seasons': season.objects.all()})


def subscribe(request):
    if request.method == "POST":
        try:
            validate_email(request.POST.get("email", ""))
            subscribers(email=request.POST["email"]).save()
            return render(request, 'mirror/subscription.html', {'ok': 'ok',
                                                                'seasons': season.objects.all()})
        except forms.ValidationError:
            return render(request, 'mirror/subscription.html', {'errors': 'неверно введен e-mail'})
    else:
        return render(request, 'mirror/subscription.html', {'errors': None,
                                                            'seasons': season.objects.all()})


def callback(request):
    if request.method == "POST":
        try:
            validate_email(request.POST.get("email", ""))
            questions(name=request.POST.get("name", ""),
                      email=request.POST.get("email", ""),
                      question=request.POST.get("text", "")).save()
            return render(request, 'mirror/callback.html', {'seasons': season.objects.all(),
                                                            'ok': 'ok'})
        except forms.ValidationError:
            return render(request, 'mirror/callback.html', {'seasons': season.objects.all(),
                                                            'errors': 'неверно введен e-mail'})
    else:
        return render(request, 'mirror/callback.html', {'seasons': season.objects.all()})


def watch(request, seasonNum, seriesNum):
    seasonCurrent = get_object_or_404(season, number=int(seasonNum))
    allSeries = seriesRus.objects.filter(obj=seasonCurrent).order_by('number')

    # последняя ли серия
    max = int(seriesRus.objects.filter(obj=seasonCurrent).order_by('-number')[0].number)
    if int(seriesNum) < max:
        lastSeries = False
    else:
        lastSeries = True

    # последний ли сезон
    maxSes = int(season.objects.all().order_by('-number')[0].number)
    if int(seasonNum) < maxSes:
        lastSeason = False
    else:
        lastSeason = True

    # последняя серия в предыдущем сезоне
    if int(seasonNum) > 1:
        prevS = season.objects.filter(number=(int(seasonNum) - 1))[0].number
        prev = int(seriesRus.objects.filter(obj=prevS).order_by('-number')[0].number)
    else:
        prev = 0

    ses = seriesRus.objects.filter(obj=seasonCurrent, number=seriesNum)[0]
    return render(request, 'mirror/watch.html', {'seasonNum': int(seasonNum),
                                                 'seriesNum': int(seriesNum),
                                                 'series': allSeries,
                                                 'seasons': season.objects.all(),
                                                 'islastSeries': lastSeries,
                                                 'islastSeason': lastSeason,
                                                 'ses': ses,
                                                 'nextNumSeries': int(seriesNum) + 1,
                                                 'nextNumSeason': int(seasonNum) + 1,
                                                 'prevSeries': int(seriesNum) - 1,
                                                 'prevSeason': int(seasonNum) - 1,
                                                 'prev': int(prev)})


def watchEngl(request, seasonNum, seriesNum):
    seasonCurrent = get_object_or_404(season, number=int(seasonNum))
    allSeries = seriesRus.objects.filter(obj=seasonCurrent).order_by('number')

    # последняя ли серия
    max = int(seriesRus.objects.filter(obj=seasonCurrent).order_by('-number')[0].number)
    if int(seriesNum) < max:
        lastSeries = False
    else:
        lastSeries = True

    # последний ли сезон
    maxSes = int(season.objects.all().order_by('-number')[0].number)
    if int(seasonNum) < maxSes:
        lastSeason = False
    else:
        lastSeason = True

    # последняя серия в предыдущем сезоне
    if int(seasonNum) > 1:
        prevS = season.objects.filter(number=(int(seasonNum) - 1))[0].number
        prev = int(seriesRus.objects.filter(obj=prevS).order_by('-number')[0].number)
    else:
        prev = 0

    rusAnalog = seriesRus.objects.filter(obj=seasonCurrent, season=int(seasonNum), number=int(seriesNum))
    ses = seriesEng.objects.filter(obj=rusAnalog)[0]
    return render(request, 'mirror/watchEng.html', {'seasonNum': int(seasonNum),
                                                    'seriesNum': int(seriesNum),
                                                    'series': allSeries,
                                                    'seasons': season.objects.all(),
                                                    'islastSeries': lastSeries,
                                                    'islastSeason': lastSeason,
                                                    'ses': ses,
                                                    'nextNumSeries': int(seriesNum) + 1,
                                                    'nextNumSeason': int(seasonNum) + 1,
                                                    'prevSeries': int(seriesNum) - 1,
                                                    'prevSeason': int(seasonNum) - 1,
                                                    'prev': int(prev)})


def setCookies(request):
    if request.method == 'GET':
        seasonNum = request.GET['season']
        seriesNum = request.GET['series']
        language = request.GET['lang']

        response = HttpResponse('ok')
        response.set_cookie('season', seasonNum, expires=(datetime.datetime.now() + datetime.timedelta(days=60)))
        response.set_cookie('series', seriesNum, expires=(datetime.datetime.now() + datetime.timedelta(days=60)))
        response.set_cookie('language', language, expires=(datetime.datetime.now() + datetime.timedelta(days=60)))
    return response

mirror/templates/mirror/callback.html
<!DOCTYPE html>
{% load static %}
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Обратная связь для сайта chernoe-zerkalo.ru">
    <meta name="keywords" content="">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>Обратная связь</title>

    <link rel="shortcut icon" href="{% static 'mirror/img/icon.ico' %}" type="image/x-icon">
    <!-- Bootstrap -->
    <link href="{% static 'mirror/css/bootstrap.css' %}" rel="stylesheet">
    <link href="{% static 'mirror/css/style.css' %}" rel="stylesheet">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>
<!-- Yandex.Metrika counter --> <script type="text/javascript"> (function (d, w, c) { (w[c] = w[c] || []).push(function() { try { w.yaCounter42563724 = new Ya.Metrika({ id:42563724, clickmap:true, trackLinks:true, accurateTrackBounce:true, webvisor:true }); } catch(e) { } }); var n = d.getElementsByTagName("script")[0], s = d.createElement("script"), f = function () { n.parentNode.insertBefore(s, n); }; s.type = "text/javascript"; s.async = true; s.src = "https://mc.yandex.ru/metrika/watch.js"; if (w.opera == "[object Opera]") { d.addEventListener("DOMContentLoaded", f, false); } else { f(); } })(document, window, "yandex_metrika_callbacks"); </script> <noscript><div><img src="https://mc.yandex.ru/watch/42563724" style="position:absolute; left:-9999px;" alt="" /></div></noscript> <!-- /Yandex.Metrika counter -->
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-91413000-1', 'auto');
  ga('send', 'pageview');

</script>
    <header>
        <nav class="navbar-inverse">
          <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
              <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span>Сезоны</span>
              </button>
              <a id="headTitle" class="navbar-brand" href="{% url 'mirror:index' %}">Black Mirror</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse sesonsNumber" id="bs-example-navbar-collapse-1">
              <ul class="nav navbar-nav navbar-right">
                <li><span id="seasons" class="hidden-xs">СЕЗОНЫ</span></li>
                  {% for key in seasons %}
                    <li><a class="hidden-xs" href="{% url 'mirror:season' key.number %}" style="margin-left:15px;">{{ key.number }}</a></li>
                    <li><a class="hidden-md hidden-lg hidden-sm" href="{% url 'mirror:season' key.number %}" style="margin-left:15px;">{{ key.number }} сезон</a></li>
                  {% endfor %}
              </ul>
            </div><!-- /.navbar-collapse -->
          </div><!-- /.container-fluid -->
        </nav>
    </header>

      <div style="height: 100%; display: table; width: 100%;">
        <div class="container" style="height: 100%; display: table; width: 100%;">
            <div class="row" style="margin-bottom: 50px;">
                <div class="col-md-6 col-md-offset-3" style="margin-top: 30px;">
                    {% if ok %}
                        <H3 style="color: green;">Ваш вопрос успешно отправлен!</H3>
                        <hr />
                    {% endif %}
                    <H3>Обратная связь</H3>
                    <hr />
                    {% if errors %}
                        <H4 style="color:red;">{{ errors }}</H4>
                        <hr />
                    {% endif %}
                    <form method="POST" action="{% url 'mirror:callback' %}">
                        {% csrf_token %}
                      <div class="form-group">
                        <label>Ваше имя</label>
                        <input type="text" name="name" class="form-control" required>
                      </div>
                      <div class="form-group">
                        <label>E-mail</label>
                        <input type="email" name="email" class="form-control" required>
                      </div>
                      <div class="form-group">
                        <label>Сообщение</label>
                        <textarea name="text" class="form-control" rows="3" required></textarea>
                      </div>
                      <button type="submit" class="btn btn-primary">Отправить</button>
                    </form>
                    <hr />
                    <H5>* также можете <a href="https://vk.com/iterate">написать мне в vk</a></H5>
                </div>
            </div>
        </div>

      <footer>
          <div class="container">
              <div class="row">
                  <div class="col-md-2 col-md-offset-1 col-xs-12 col-sm-6">
                    <a class="btn btn-success btn-sm" href="{% url 'mirror:subscribe' %}" role="button" style="position:relative; bottom: 9px; left: 25px;">Хочу узнавать о новых сериях</a>
                  </div>
                  <div class="col-md-3 col-md-offset-1 col-xs-12 col-sm-6">
                    <a class="btn btn-success btn-sm" href="{% url 'mirror:callback' %}" role="button" style="position:relative; bottom: 9px; left: 25px;">Обратная связь</a>
                  </div>
              </div>
          </div>
      </footer>
      </div>

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="{% static 'mirror/js/bootstrap.min.js' %}"></script>
  </body>
</html>

mirror/templates/mirror/season.html
<!DOCTYPE html>
{% load static %}
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="keywords" content="">
    <meta name="description" content="Описание и все серии {{ season.number }} сезона сериала Черное Зеркало ">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>Черное зеркало {{ season.number }} сезон</title>

    <link rel="shortcut icon" href="{% static 'mirror/img/icon.ico' %}" type="image/x-icon">
    <!-- Bootstrap -->
    <link href="{% static 'mirror/css/bootstrap.css' %}" rel="stylesheet">
    <link href="{% static 'mirror/css/style.css' %}" rel="stylesheet">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>
<!-- Yandex.Metrika counter --> <script type="text/javascript"> (function (d, w, c) { (w[c] = w[c] || []).push(function() { try { w.yaCounter42563724 = new Ya.Metrika({ id:42563724, clickmap:true, trackLinks:true, accurateTrackBounce:true, webvisor:true }); } catch(e) { } }); var n = d.getElementsByTagName("script")[0], s = d.createElement("script"), f = function () { n.parentNode.insertBefore(s, n); }; s.type = "text/javascript"; s.async = true; s.src = "https://mc.yandex.ru/metrika/watch.js"; if (w.opera == "[object Opera]") { d.addEventListener("DOMContentLoaded", f, false); } else { f(); } })(document, window, "yandex_metrika_callbacks"); </script> <noscript><div><img src="https://mc.yandex.ru/watch/42563724" style="position:absolute; left:-9999px;" alt="" /></div></noscript> <!-- /Yandex.Metrika counter -->
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-91413000-1', 'auto');
  ga('send', 'pageview');

</script>
    <header>
        <nav class="navbar-inverse">
          <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
              <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span>Сезоны</span>
              </button>
              <a id="headTitle" class="navbar-brand" href="{% url 'mirror:index' %}">Black Mirror</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse sesonsNumber" id="bs-example-navbar-collapse-1">
              <ul class="nav navbar-nav navbar-right">
                <li><span id="seasons" class="hidden-xs">СЕЗОНЫ</span></li>
                  {% for ses in seasons %}
                    {% if ses.number == season.number %}
                        <li>
                            <a class="hidden-xs" href="{% url 'mirror:season' ses.number %}" style="margin-left:15px;">
                            <span id="current-watch">
                                {{ ses.number }}
                            </span>
                            </a>
                        </li>
                        <li>
                            <a class="hidden-md hidden-lg hidden-sm" href="{% url 'mirror:season' ses.number %}" style="margin-left:15px;">
                                <span id="current-watch-rectangle">
                                    {{ ses.number }} сезон
                                </span>
                                </a>
                        </li>
                    {% else %}
                        <li>
                            <a class="hidden-xs" href="{% url 'mirror:season' ses.number %}" style="margin-left:15px;">
                                {{ ses.number }}
                            </a>
                        </li>
                        <li>
                            <a class="hidden-md hidden-lg hidden-sm" href="{% url 'mirror:season' ses.number %}" style="margin-left:15px;">
                                {{ ses.number }} сезон
                            </a>
                        </li>
                    {% endif %}
                  {% endfor %}
              </ul>
            </div><!-- /.navbar-collapse -->
          </div><!-- /.container-fluid -->
        </nav>
    </header>

      <div style="height: 100%; display: table; width: 100%;">
          <content style="display: table-row; height: 30%;">
            <div class="container" style="margin-top: 10px; margin-bottom: 15px;">
                <!-- text description -->
                <div class="row">
                    <div class="col-md-10 col-md-offset-1" style="padding-left: 40px;
                                                                  padding-right: 35px;">
                        <H1 style="font-size: 28px; margin-bottom: 20px;">
                            Черное зеркало: {{ season.number }} сезон
                        </H1>
                        <p style="color: #333;">
                            {{ season.description|safe }}
                        </p>
                    </div>
                </div>
            </div>
          </content>


          <div id="watch-series" class="container-fluid" style="display: table-row; height: 90%;">
              <div class="container">
                  <div class="row">
                      <div class="col-md-10 col-md-offset-1" style="padding-left: 40px;
                                                                    padding-right: 35px;">
                        <H3 style="margin-bottom: 20px;">Список серий</H3>
                        <div class="clear: both;"></div>
                        <div style="position:relative; right: 15px; bottom: 20px;">
                            {% for s in series %}
                                <a href="{% url 'mirror:watch' season.number s.number %}">
                                    <div style="background-image: url({% static ''%}/mirror/img/holder/{{s.season}}{{s.number}}.jpg);" class="icon-serie">
                                        <div class="serie-name">
                                            <span class="seriesTXT">{{ s.number }} серия</span>
                                        </div>
                                        <div class="serie-desc">
                                            <span class="seriesTXT">{{ s.name }}</span>
                                        </div>
                                        <div class="serie-time">
                                            <span class="seriesTXT">{{ s.duration }}</span>
                                        </div>
                                    </div>
                                </a>
                            {% endfor %}
                        </div>
                        <div style="clear: both;"></div>
                      </div>
                  </div>
              </div>
          </div>

          <footer>
              <div class="container">
                  <div class="row">
                      <div class="col-md-2 col-md-offset-1 col-xs-12 col-sm-6">
                        <a class="btn btn-success btn-sm" href="{% url 'mirror:subscribe' %}" role="button" style="position:relative; bottom: 9px; left: 25px;">Хочу узнавать о новых сериях</a>
                      </div>
                      <div class="col-md-3 col-md-offset-1 col-xs-12 col-sm-6">
                        <a class="btn btn-success btn-sm" href="{% url 'mirror:callback' %}" role="button" style="position:relative; bottom: 9px; left: 25px;">Обратная связь</a>
                      </div>
                  </div>
              </div>
          </footer>
      </div>

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="{% static 'mirror/js/bootstrap.min.js' %}"></script>
  </body>
</html>